# Generated by Django 5.1.3 on 2024-11-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycon', '0002_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='topic',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
